---
ID: e20518bb-1f4d-467f-bae0-11fc2f939c5e
Parent: fff5f245-ffc0-4022-a998-9b07aa5e761f
Template: fff5f245-ffc0-4022-a998-9b07aa5e761f
Path: /sitecore/templates/Habitat/Framework/LocalDatasource/Local Datasource Folder/__Standard Values
