---
ID: af244e6f-ef24-4e60-8c85-ff18a9d8a54f
Parent: 4c82b6dd-fe7c-4144-bcb3-f21b4080568f
Template: 4c82b6dd-fe7c-4144-bcb3-f21b4080568f
Path: /sitecore/templates/Habitat/Framework/Multisite/Settings Folder/__Standard Values
